export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const MEMORY_SIZES = {
  KILOBYTE: 1024,
  HUNDRED_MB: 100,
  NINETY_PERCENT: 90,
} as const;

export const CONTENT_LIMITS = {
  PREVIEW_LENGTH: 100,
  FIFTY_LIMIT: 50,
  TEN_LIMIT: 10,
  BATCH_SIZE: 5,
  MAX_CONCURRENT_REQUESTS: 3,
  SEARCH_RESULTS_LIMIT: 5,
  FOUR_DECIMAL_PLACES: 4,
  CONTENT_SNIPPET: 300,
  MAX_FALLBACK_PAGES: 3,
  MAX_DIRECT_SEARCH_PAGES: 5,
  MIN_WORD_LENGTH: 3,
} as const;

export const TIMEOUTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  BATCH_DELAY: 2000,
  QUERY_TIMEOUT_MS: 5000,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 100,
  DEFAULT_PAGE: 1,
} as const;
