import { HTTP_STATUS } from '@constants/index';

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  OPTIONS = 'OPTIONS',
  PATCH = 'PATCH',
}

export enum HttpStatusCode {
  OK = HTTP_STATUS.OK,
  CREATED = HTTP_STATUS.CREATED,
  BAD_REQUEST = HTTP_STATUS.BAD_REQUEST,
  UNAUTHORIZED = HTTP_STATUS.UNAUTHORIZED,
  FORBIDDEN = HTTP_STATUS.FORBIDDEN,
  NOT_FOUND = HTTP_STATUS.NOT_FOUND,
  METHOD_NOT_ALLOWED = HTTP_STATUS.METHOD_NOT_ALLOWED,
  INTERNAL_SERVER_ERROR = HTTP_STATUS.INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE = HTTP_STATUS.SERVICE_UNAVAILABLE,
}
